#!/bin/bash
SCRIPT_PATH="$0"
if [[ -z "$BUTTERFLY_HOME" ]]; then
    BUTTERFLY_HOME=$(dirname "$SCRIPT_PATH")
    export BUTTERFLY_HOME
fi

java -cp $BUTTERFLY_HOME"/lib/*":$BUTTERFLY_HOME"/extensions/*" \
    -Dloader.main=com.paypal.butterfly.cli.ButterflyCliApp \
    org.springframework.boot.loader.PropertiesLauncher $*
