package com.paypal.butterfly.rest.model;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Metrics generated by a transformation
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TransformationMetrics {
}
